
import {
  Square,
  Type,
  ImageIcon,
  Star,
  Heart,
  Home,
  User,
  Settings,
  Mail,
  Phone,
  Calendar,
  MapPin,
  Camera,
  Music,
  Video,
  Download,
  Upload,
  Search,
  Bell,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Edit,
  Trash,
  Plus,
  Minus,
  Check,
  X,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  QrCode,
  Barcode,
} from "lucide-react"
import { ElementType } from "@/types/visual-editor"

// Lista de ícones disponíveis
export const availableIcons = {
  star: Star,
  heart: Heart,
  home: Home,
  user: User,
  settings: Settings,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  mapPin: MapPin,
  camera: Camera,
  music: Music,
  video: Video,
  download: Download,
  upload: Upload,
  search: Search,
  bell: Bell,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
}

// Lista de elementos disponíveis
export const availableElements = [
  { type: "frame" as ElementType, name: "Frame", icon: Square },
  { type: "text" as ElementType, name: "Text", icon: Type },
  { type: "image" as ElementType, name: "Image", icon: ImageIcon },
  { type: "icon" as ElementType, name: "Icon", icon: Star },
  { type: "QRcode" as ElementType, name: "Qrcode", icon: QrCode  },
  { type: "barcode" as ElementType, name: "Barcode", icon: Barcode  },
]
